name: Flutter Web

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        #flutter-version: '1.12.x'
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - run: flutter upgrade
    - run: flutter config --enable-web
    - run: flutter packages get
    - run: flutter build web
    - run: git init
    - run: git config user.name  "CI"
    - run: git config user.email "flutter-ci@github.com"
    - run: git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/dleurs/flutter_hello_world_web.git
    - run: git checkout -b gh-pages
    - run: git add .
    - run: git commit -m "Updated docs" --allow-empty
    - run: git push --force secure-origin gh-pages
